language: python

cache:
  - ccache
  - pip

jobs:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
  allow_failures:
    - os: linux
      python: 2.7

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create --name=dense-fusion python=$TRAVIS_PYTHON_VERSION -q -y
  - source activate dense-fusion 
  - pip install opencv-python
  - pip install -r requirements.txt
  - pip install -e .

before_script:
  - pip install flake8
  - pip install hacking
  - pip install autopep8

script:
  - flake8 .

notifications:
  email: false
